import {
  CONF_LIVE_CONTROLS_TIMELINE_MODE,
  CONF_LIVE_CONTROLS_TIMELINE_PAN_MODE,
  CONF_LIVE_CONTROLS_TIMELINE_STYLE,
  CONF_MEDIA_VIEWER_CONTROLS_TIMELINE_MODE,
  CONF_MEDIA_VIEWER_CONTROLS_TIMELINE_PAN_MODE,
  CONF_MEDIA_VIEWER_CONTROLS_TIMELINE_STYLE,
} from '../../const.js';

export const SCRUBBING_PROFILE = {
  [CONF_LIVE_CONTROLS_TIMELINE_MODE]: 'below' as const,
  [CONF_LIVE_CONTROLS_TIMELINE_STYLE]: 'ribbon' as const,
  [CONF_LIVE_CONTROLS_TIMELINE_PAN_MODE]: 'seek' as const,

  [CONF_MEDIA_VIEWER_CONTROLS_TIMELINE_MODE]: 'below' as const,
  [CONF_MEDIA_VIEWER_CONTROLS_TIMELINE_STYLE]: 'ribbon' as const,
  [CONF_MEDIA_VIEWER_CONTROLS_TIMELINE_PAN_MODE]: 'seek' as const,
};
