import { expect, it } from 'vitest';
import { LOW_PERFORMANCE_PROFILE } from '../../../src/config/profiles/low-performance';

it('low performance profile', () => {
  expect(LOW_PERFORMANCE_PROFILE).toEqual({
    'cameras_global.image.refresh_seconds': 10,
    'cameras_global.live_provider': 'image',
    'cameras_global.triggers.occupancy': false,
    'live.auto_mute': 'never',
    'live.controls.thumbnails.mode': 'none',
    'live.controls.thumbnails.show_details': false,
    'live.controls.thumbnails.show_download_control': false,
    'live.controls.thumbnails.show_favorite_control': false,
    'live.controls.thumbnails.show_timeline_control': false,
    'live.controls.timeline.show_recordings': false,
    'live.controls.title.mode': 'none',
    'live.draggable': false,
    'live.lazy_unload': 'all',
    'live.show_image_during_load': false,
    'live.transition_effect': 'none',
    'media_gallery.controls.thumbnails.show_details': false,
    'media_gallery.controls.thumbnails.show_download_control': false,
    'media_gallery.controls.thumbnails.show_favorite_control': false,
    'media_gallery.controls.thumbnails.show_timeline_control': false,
    'media_viewer.auto_mute': 'never',
    'media_viewer.auto_pause': 'never',
    'media_viewer.auto_play': 'never',
    'media_viewer.controls.next_previous.style': 'chevrons',
    'media_viewer.controls.thumbnails.mode': 'none',
    'media_viewer.controls.thumbnails.show_details': false,
    'media_viewer.controls.thumbnails.show_download_control': false,
    'media_viewer.controls.thumbnails.show_favorite_control': false,
    'media_viewer.controls.thumbnails.show_timeline_control': false,
    'media_viewer.controls.timeline.show_recordings': false,
    'media_viewer.controls.title.mode': 'none',
    'media_viewer.draggable': false,
    'media_viewer.snapshot_click_plays_clip': false,
    'media_viewer.transition_effect': 'none',
    'menu.buttons.frigate.enabled': false,
    'menu.buttons.media_player.enabled': false,
    'menu.buttons.timeline.enabled': false,
    'menu.style': 'outside',
    'performance.features.animated_progress_indicator': false,
    'performance.features.media_chunk_size': 10,
    'performance.style.border_radius': false,
    'performance.style.box_shadow': false,
    'timeline.controls.thumbnails.mode': 'none',
    'timeline.controls.thumbnails.show_details': false,
    'timeline.controls.thumbnails.show_download_control': false,
    'timeline.controls.thumbnails.show_favorite_control': false,
    'timeline.controls.thumbnails.show_timeline_control': false,
    'timeline.show_recordings': false,
  });
});
